### ISSUE TITLE
User model crashes when delete Zone

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2293]
The crash occurs when deleting the zone with the OpenStudio application or the SketchUp plugin. I reproduced on 1.12.0 on mac. User file supplied is 1.12.0 file.
https://unmethours.com/question/18801/zone-has-no-surfaces/?comment=18806#post-id-18806

Here is link to file
https://github.com/NREL/OpenStudio-files/tree/master/User%20Files/Wesley%20Stockton

Users says it it a clean model vs. one upgrade from older versions of OpenStudio. User suggested that this may be caused by cloning a zone, but I can't reproduce this issue on a new model. When I clone a zone that is on an air loop, the cloned zone is no longer on the air loop.

As shown on the two screenshots below there is an inconsistency in the thermal zone tab and hvac tab if "Thermal Zone 0" is on the air loop or not. I expect the root cause of this is related to the crash.

![screenshot 2016-07-07 08 44 29](https://cloud.githubusercontent.com/assets/4857055/16657707/a8d2cc70-4420-11e6-822a-4c83d5390d3b.png)

![screenshot 2016-07-07 08 44 45](https://cloud.githubusercontent.com/assets/4857055/16657711/ae3ba740-4420-11e6-9345-7fd0b706bba2.png)

Here is zone and related objects
`
OS:ThermalZone,
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}, !- Handle
  Thermal Zone 0,                         !- Name
  ,                                       !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  ,                                       !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ,                                       !- Zone Outside Convection Algorithm
  ,                                       !- Zone Conditioning Equipment List Name
  {bbd03621-8e50-42ef-8031-e8a22dc6666a}, !- Zone Air Inlet Port List
  {ebca5893-436a-4163-a594-1b2d73f8b67c}, !- Zone Air Exhaust Port List
  {aaafa898-6aee-4bf4-9fe6-2a50b6582260}, !- Zone Air Node Name
  ,                                       !- Zone Return Air Node Name
  ,                                       !- Primary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Primary Daylighting Control
  ,                                       !- Secondary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Secondary Daylighting Control
  ,                                       !- Illuminance Map Name
  {16d7438b-ac73-4017-8fc8-ba8a968cf21a}, !- Group Rendering Name
  {aacb44ac-9102-482d-a953-b06d1405417c}, !- Thermostat Name
  No,                                     !- Use Ideal Air Loads
  ;                                       !- Humidistat Name

OS:Node,
  {9b79f550-ef97-4b31-aff7-ada188308db6}, !- Handle
  Node 1,                                 !- Name
  {aaafa898-6aee-4bf4-9fe6-2a50b6582260}, !- Inlet Port
  ;                                       !- Outlet Port

OS:Connection,
  {aaafa898-6aee-4bf4-9fe6-2a50b6582260}, !- Handle
  {5b1dd72c-e1bb-40b6-9708-e335bdd22bbf}, !- Name
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}, !- Source Object
  11,                                     !- Outlet Port
  {9b79f550-ef97-4b31-aff7-ada188308db6}, !- Target Object
  2;                                      !- Inlet Port

OS:PortList,
  {bbd03621-8e50-42ef-8031-e8a22dc6666a}, !- Handle
  Port List 1,                            !- Name
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}, !- HVAC Component
  {df42acda-13bf-4e5b-b340-81166ffdaee1}; !- Port 1

OS:PortList,
  {ebca5893-436a-4163-a594-1b2d73f8b67c}, !- Handle
  Port List 2,                            !- Name
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}; !- HVAC Component

OS:Sizing:Zone,
  {f7925770-cbc8-47a9-8221-48717705ad1e}, !- Handle
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}, !- Zone or ZoneList Name
  SupplyAirTemperature,                   !- Zone Cooling Design Supply Air Temperature Input Method
  14,                                     !- Zone Cooling Design Supply Air Temperature {C}
  11.11,                                  !- Zone Cooling Design Supply Air Temperature Difference {deltaC}
  SupplyAirTemperature,                   !- Zone Heating Design Supply Air Temperature Input Method
  40,                                     !- Zone Heating Design Supply Air Temperature {C}
  11.11,                                  !- Zone Heating Design Supply Air Temperature Difference {deltaC}
  0.0085,                                 !- Zone Cooling Design Supply Air Humidity Ratio {kg-H2O/kg-air}
  0.008,                                  !- Zone Heating Design Supply Air Humidity Ratio {kg-H2O/kg-air}
  ,                                       !- Zone Heating Sizing Factor
  ,                                       !- Zone Cooling Sizing Factor
  DesignDay,                              !- Cooling Design Air Flow Method
  ,                                       !- Cooling Design Air Flow Rate {m3/s}
  ,                                       !- Cooling Minimum Air Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Cooling Minimum Air Flow {m3/s}
  ,                                       !- Cooling Minimum Air Flow Fraction
  DesignDay,                              !- Heating Design Air Flow Method
  ,                                       !- Heating Design Air Flow Rate {m3/s}
  ,                                       !- Heating Maximum Air Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Heating Maximum Air Flow {m3/s}
  ,                                       !- Heating Maximum Air Flow Fraction
  ,                                       !- Design Zone Air Distribution Effectiveness in Cooling Mode
  ,                                       !- Design Zone Air Distribution Effectiveness in Heating Mode
  No,                                     !- Account for Dedicated Outdoor Air System
  NeutralSupplyAir,                       !- Dedicated Outdoor Air System Control Strategy
  autosize,                               !- Dedicated Outdoor Air Low Setpoint Temperature for Design {C}
  autosize;                               !- Dedicated Outdoor Air High Setpoint Temperature for Design {C}

OS:ZoneHVAC:EquipmentList,
  {651674c7-3dfe-4986-96c4-d87b4fb4029a}, !- Handle
  Zone HVAC Equipment List 1,             !- Name
  {9e854690-8616-4f69-a50e-1d1ed78bed1b}, !- Thermal Zone
  {40ef94e8-56b6-4996-a33a-afe78203a75c}, !- Zone Equipment 1
  1,                                      !- Zone Equipment Cooling Sequence 1
  1;                                      !- Zone Equipment Heating or No-Load Sequence 1`

**Comment by DavidGoldwasser** [comment]
When I deleted those objects the crash was gone but I got this error about node 7. @kbenne if you can clean this up better so it runs we can send updated file to user while we try to identify/fix the issue.

`   ** Warning ** GetAirPathData: AirLoopHVAC="GAS FIRED FURNACE" has no Controllers.
   ** Severe  ** Node NODE 7 connects to no component
   **   ~~~   ** Occurs in Supply Air Path=GAS FIRED FURNACE NODE 5 SUPPLY PATH
   **   ~~~   ** Check the connection to a ZoneHVAC:EquipmentConnections object
   **   ~~~   ** Check if this component is missing from the Supply Air Path
   **  Fatal  ** Preceding errors cause termination`

**Comment by DavidGoldwasser** [comment]
@kbenne editing the file with a text editor is tricky because I need to deal with nodes, so I thought I'd try to use use a measure, but it crashed as well. Here is the code I used.

`    zone = model.getModelObjectByName("Thermal Zone 0").get.to_ThermalZone.get
    runner.registerInfo("Removing #{zone.name}")
    zone.remove`

And here is what log info, not sure if it helps.

> -- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0043 e:000042 CFUNC  :remove
c:0003 p:0099 s:0040 e:000039 METHOD /private/var/folders/83/rcnbz4dd5qqgf7rpc69354_x0g1kng/T/OpenStudio.f63472/ApplyMeasureNow/UserScript/user_script.rb:43
c:0002 p:1590 s:0033 E:000600 EVAL   in.rb:355 [FINISH]
c:0001 p:0000 s:0002 E:000f88 TOP    [FINISH]

in.rb:355:in `<main>'
/private/var/folders/83/rcnbz4dd5qqgf7rpc69354_x0g1kng/T/OpenStudio.f63472/ApplyMeasureNow/UserScript/user_script.rb:43:in `run'
/private/var/folders/83/rcnbz4dd5qqgf7rpc69354_x0g1kng/T/OpenStudio.f63472/ApplyMeasureNow/UserScript/user_script.rb:43:in `remove'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: in.rb

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/pathname.bundle
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb
   20 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiescore.bundle
   21 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiestime.bundle
   22 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesdata.bundle
   23 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesplot.bundle
   24 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesgeometry.bundle
   25 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiessql.bundle
   26 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesbcl.bundle
   27 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiescloud.bundle
   28 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesunits.bundle
   29 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesidd.bundle
   30 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesidf.bundle
   31 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilitiesfiletypes.bundle
   32 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioutilities.bundle
   33 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodel.bundle
   34 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelcore.bundle
   35 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelsimulation.bundle
   36 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelresources.bundle
   37 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelgeometry.bundle
   38 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelhvac.bundle
   39 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelrefrigeration.bundle
   40 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodelgenerators.bundle
   41 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioenergyplus.bundle
   42 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioradiance.bundle
   43 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiogbxml.bundle
   44 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioairflow.bundle
   45 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioosversion.bundle
   46 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioruleset.bundle
   47 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiorunmanager.bundle
   48 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioproject.bundle
   49 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioanalysisdriver.bundle
   50 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiomodeleditor.bundle
   51 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioanalysis.bundle
   52 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiolib.bundle
   53 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudioisomodel.bundle
   54 /Applications/OpenStudio 1.12.0/Ruby/openstudio/openstudiosdd.bundle
   55 /Applications/OpenStudio 1.12.0/Ruby/openstudio.rb
   56 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by DavidGoldwasser** [comment]
Ok, so I was able to clean up in the GUI by following these steps. I was surprised that Step 1 was required, but it seemed to be.

1. Delete the air loop
2. Go to Thermal Zone tab, select the terminal that shows up for "Thermal Zone 0" and delete it by clicking the black and white "x" in the edit tab.
3. Delete "Thermal Zone 0"
4. Add back the air loop and connect Thermal Zone 1 and 2.

This doesn't make the issue invalid, we still should fix the crash.

**Comment by DavidGoldwasser** [comment]
Closing this. Will re-open if we see it happen more.
