### ISSUE TITLE
Diag.rb error using integer_sequence

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2583]
Specified integer_sequence distribution in PAT 2.1.1 for diagonal sampling and I get this error:

```
opt/openstudio/server/lib/analysis_library/diag.rb failed with undefined method `size' for nil:NilClass, /opt/openstudio/server/app/models/variable.rb:349:in `map_discrete_hash_to_array' /opt/openstudio/server/app/models/variable.rb:268:in `block in pivot_array' /usr/local/bundle/gems/mongoid-5.1.6/lib/mongoid/contextual/mongo.rb:676:in `yield_document' /usr/local/bundle/gems/mongoid-5.1.6/lib/mongoid/contextual/mongo.rb:122:in `block in each' /usr/local/bundle/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:45:in `block in each' /usr/local/bundle/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `block in each' /usr/local/bundle/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each' /usr/local/bundle/gems/mongo-2.4.1/lib/mongo/cursor.rb:110:in `each' /usr/local/bundle/gems/mongo-2.4.1/lib/mongo/collection/view/iterable.rb:44:in `each' /usr/local/bundle/gems/mongoid-5.1.6/lib/mongoid/query_cache.rb:221:in `each' /usr/local/bundle/gems/mongoid-5.1.6/lib/mongoid/contextual/mongo.rb:121:in `each' /usr/local/bundle/gems/mongoid-5.1.6/lib/mongoid/contextual.rb:20:in `each' /opt/openstudio/server/app/models/variable.rb:252:in `pivot_array' /opt/openstudio/server/lib/analysis_library/diag.rb:90:in `perform' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:84:in `block in invoke_job' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/backend/base.rb:81:in `invoke_job' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block (2 levels) in run' /usr/local/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout' /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `call' /usr/local/lib/ruby/2.2.0/timeout.rb:98:in `timeout' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:230:in `block in run' /usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:229:in `run' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `block in reserve_and_run_one_job' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:306:in `reserve_and_run_one_job' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:213:in `block in work_off' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `times' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:212:in `work_off' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:175:in `block (4 levels) in start' /usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:174:in `block (3 levels) in start' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:173:in `block (2 levels) in start' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:172:in `loop' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:172:in `block in start' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/plugins/clear_locks.rb:7:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:79:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:61:in `block in initialize' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:79:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:79:in `block in add' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `call' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:66:in `execute' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/lifecycle.rb:40:in `run_callbacks' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/worker.rb:171:in `start' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/command.rb:132:in `run' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/command.rb:120:in `block in run_process' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `call' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `block in start_proc' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `call' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `start_proc' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/application.rb:296:in `start' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/controller.rb:59:in `run' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons.rb:197:in `block in run_proc' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `call' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions' /usr/local/bundle/gems/daemons-1.2.4/lib/daemons.rb:196:in `run_proc' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/command.rb:118:in `run_process' /usr/local/bundle/gems/delayed_job-4.1.2/lib/delayed/command.rb:94:in `daemonize' /opt/openstudio/server/bin/delayed_job:6:in `<main>'
```

If I switch from integer_sequence to discrete, it works correctly. But we want to use integer_sequence for ResStock.

@rHorsey @asparke2

**Comment by shorowit** [comment]
JSON file:

[analysis.json.txt](https://github.com/NREL/OpenStudio/files/944283/analysis.json.txt)

**Comment by rHorsey** [comment]
Kat has fixed this on the PAT side with https://github.com/NREL/OpenStudio-PAT/commit/96ab4b271d7ae0eb77781528a06806dcf62b67b8 - Brain's looking at another potential issue.

**Comment by rHorsey** [comment]
Fixed and confirmed PAT side. Cheers

**Comment by rHorsey** [comment]
I think @asparke2 confirmed this fix a few weeks ago. If so this can be closed.

**Comment by asparke2** [comment]
Confirmed that this works in developer build by modifying ComStock.
