### ISSUE TITLE
OpenStudio fails to run with an ERROR

### ISSUE THREAD

**Issue by Dinosaver** [NREL/OpenStudio#2660]
Win10 Pro, only restart of OS resolves the problem
The run log:
[16:11:10.541588 ERROR] :/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb failed with Permission denied @ rb_sysopen - C:/Users/Nikolay/AppData/Local/Temp/OpenStudioApp.Qr2744/resources/run/energyplus.exe, :/ruby/2.2.0/fileutils.rb:1392:in `initialize'
:/ruby/2.2.0/fileutils.rb:1392:in `open'
:/ruby/2.2.0/fileutils.rb:1392:in `block in copy_file'
:/ruby/2.2.0/fileutils.rb:1391:in `open'
:/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
:/ruby/2.2.0/fileutils.rb:485:in `copy_file'
:/ruby/2.2.0/fileutils.rb:402:in `block in cp'
:/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
:/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
:/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
:/ruby/2.2.0/fileutils.rb:401:in `cp'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:66:in `block in prepare_energyplus_dir'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:56:in `each'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:56:in `prepare_energyplus_dir'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:94:in `call_energyplus'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/jobs/run_energyplus.rb:39:in `perform'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/run.rb:256:in `step'
:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/run.rb:210:in `run'
:/openstudio_cli.rb:802:in `execute'
:/openstudio_cli.rb:620:in `execute'
:/openstudio_cli.rb:1515:in `<main>'
eval:85:in `eval'
eval:85:in `require_embedded_absolute'
eval:70:in `block in require'
eval:64:in `each'
eval:64:in `require'
eval:2:in `<main>'
[16:11:10.541588 ERROR] Found error in state 'simulation' with message ["undefined method `each' for nil:NilClass::/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:30:in `clean_directory'\n:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:166:in `ensure in call_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/util/energyplus.rb:169:in `call_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/jobs/run_energyplus.rb:39:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/run.rb:256:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.2.1/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:802:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1515:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'"]}

**Comment by evanweaver** [comment]
@kbenne this maybe an issue with copying the dlls.

**Comment by macumber** [comment]
I suspect this is no longer relevant as we don't copy energyplus into run dir anymore

https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/util/energyplus.rb#L60

**Comment by jmarrec** [comment]
I agree with macumber on paper. Closed until someone can actually reproduce this.
