### ISSUE TITLE
PAT 2.1.2 Error: Infinity not allowed in JSON

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2670]
All of my datapoints (except the baseline where I run only OpenStudio Results measure) are failing, I don't understand why. I can see that the measures I'm applying are working correctly.

if I open localResults, pick a datapoint randomly, and extract the zip to look at `run.log` here's the end of it:

```
[14:59:17.978161 DEBUG] Passing measure OpenStudioResults of type ModelMeasure
[14:59:17.978240 INFO] Finished applying OpenStudio measures.
[14:59:17.978260 DEBUG] Communicating measure output attributes to the output adapter
[14:59:17.979185 ERROR] Found error in state 'os_measures' with message ["837: Infinity not allowed in JSON:/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/json/common.rb:285:in `generate'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/json/common.rb:285:in `pretty_generate'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/adapters/output/local.rb:69:in `block in communicate_measure_attributes'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/adapters/output/local.rb:68:in `open'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/adapters/output/local.rb:68:in `communicate_measure_attributes'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/jobs/run_os_measures.rb:57:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/run.rb:259:in `step'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/run.rb:210:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:173:in `block in perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:168:in `open'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:168:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/performable_method.rb:26:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:98:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:98:in `timeout'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:137:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:125:in `block in run_process'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `block in start_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `start_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:296:in `start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/controller.rb:59:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons.rb:197:in `block in run_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons.rb:196:in `run_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:123:in `run_process'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:98:in `daemonize'\nbin/delayed_job:6:in `<main>'"]}

```

**Comment by jmarrec** [comment]
I think I found why. In temp_data/measures/ only my OpenStudio Results (BCL) measure is there. When trying to run the .osw, it cannot find the measure folder for the other measures, and therefore returns this Infinity error
in PATProject/Measures I also have only the OpenStudio Results measure and not the other ones.

**Comment by ljbrackney** [comment]
Can you try deleting all the Measures from your project and re-adding them?  I had a similar problem last night and that fixed it.

**Comment by jmarrec** [comment]
I found the culprit.

It's a BCL measure: https://bcl.nrel.gov/node/37850

It's using runner.registerValue and some of it is returning infinity. It's using space.infiltrationDesignFlowPerExteriorWallArea ==> Infinity, when you have no exterior wall area.

The guilty procedure is here, called from space.infiltrationDesignFlowPerExteriorWallArea: https://github.com/NREL/OpenStudio/blob/72e4961a2d6547dcb40be48f722345b5691e3a74/openstudiocore/src/model/SpaceInfiltrationDesignFlowRate.cpp#L491

**Comment by macumber** [comment]
Need to fix that method as well as the fact that this crashes PAT

**Comment by jmarrec** [comment]
This should have been an OptionalDouble to begin with I guess. But changing this might not be backwards compatible and break some measures... Maybe it's good enough to have it return 0 instead?

**Comment by macumber** [comment]
Rescoping to just prevent returning infinity from API methods

**Comment by macumber** [comment]
PAT component moved to PAT repo

**Comment by DavidGoldwasser** [comment]
I am hitting this in OpenStudio 3.1.0 with our model articulation workflow whenever I add a basement to it. An internal URBANopt project had it an issue with basements a while ago that was not addressed, it could be this. This is a confusing issue to troubleshoot because there are no step errors in the measure. All model measures run, reporting measures don't and there are no simulation results (other than sizing run in measure). So it failed between model measures finishing and simulation starting (I think before forward translation).

`[09:22:26.600101 ERROR] Found error in state 'os_measures' with message ["862: Infinity not allowed in JSON::/ruby/2.5.0/json/common.rb:286:in `generate'\n:/ruby/2.5.0/json/common.rb:286:in `pretty_generate'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/adapters/output/local.rb:111:in `block in communicate_measure_attributes'\neval:427:in `open'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/adapters/output/local.rb:110:in `communicate_measure_attributes'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/jobs/run_os_measures.rb:75:in `perform'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:292:in `step'\n:/ruby/2.5.0/gems/openstudio-workflow-2.1.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:971:in `execute'\n:/openstudio_cli.rb:761:in `execute'\n:/openstudio_cli.rb:1755:in `<main>'\neval:175:in `eval'\neval:175:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `<main>'"]}
`

Here is the osw on a repo with measure that can be run in 3.1.0 to replicate this or test fixes
https://github.com/DavidGoldwasser/osw2osa/blob/bug_testing_pre_bundled/run/workflows/basement/in.osw

I confirmed removing view model (which is a model measure) and  openstudio results doesn't change this. The only fix is changing argument for `num_stories_below_grade` to 0.

**Comment by DavidGoldwasser** [comment]
I had a theory that this might be related to using integer argument with a non-zero value, but that isn't the case. The same create_bar measure has an integer argument for number of party walls for each cardinal direction. That doesn't create any issues. Below is what my updated test looked like

`      {
         "arguments" : 
         {
            "bar_sep_dist_mult" : "2.0",
            "bldg_type_a" : "MediumOffice",
            "make_mid_story_surfaces_adiabatic" : true,
            "num_stories_above_grade" : "2.0",
            "num_stories_below_grade" : "0",
            "party_wall_stories_north" : "1",
            "perim_mult" : "1.75",
            "template" : "90.1-2004",
            "total_bldg_floor_area" : "25000"
         },
         "measure_dir_name" : "create_bar_from_doe_building_type_ratios"
      },`

**Comment by jmarrec** [comment]
unclear what the action items are
