### ISSUE TITLE
PAT Crashes due to non ascii characters

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2671]
Using my own copy for the BCL measure [tariff_selection_generic](https://bcl.nrel.gov/node/82925) I added new utility .idf files in /resources/ folder, in which I was using IDF comments including the € sign. For eg:

```
! Flat type: 40€ incl VAT per year for fixed contract price
!  0.03958454 €/kWh
```

Turns out this makes PAT blow up. It runs just fine when I use the OpenStudio CLI...

The problem is the € sign, if I change that to "EUR" instead, PAT runs fine... I'm not sure I understand why exactly it does work in the CLI and crashes in PAT, but this seems like an issue to me (and one that was quite hard to pinpoint too...)

----

**Error log**

```
[11:09:38.000917 ERROR] Found error in state 'ep_measures' with message ["\"\\xE2\" from ASCII-8BIT to UTF-8:/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/util/model.rb:94:in `write'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/util/model.rb:94:in `<<'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/util/model.rb:94:in `block in save_idf'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/util/model.rb:94:in `open'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/util/model.rb:94:in `save_idf'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/jobs/run_ep_measures.rb:51:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/run.rb:259:in `step'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.0/lib/openstudio/workflow/run.rb:210:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:173:in `block in perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:168:in `open'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/app/workers/run_simulate_data_point.rb:168:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/performable_method.rb:26:in `perform'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:98:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/timeout.rb:98:in `timeout'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:137:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:125:in `block in run_process'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:266:in `block in start_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:275:in `start_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/application.rb:296:in `start'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/controller.rb:59:in `run'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons.rb:197:in `block in run_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `call'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/daemons-1.2.4/lib/daemons.rb:196:in `run_proc'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:123:in `run_process'\n/Applications/OpenStudio-2.1.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/delayed_job-4.1.3/lib/delayed/command.rb:98:in `daemonize'\nbin/delayed_job:6:in `<main>'"]}
[11:09:38.001056 INFO] Finished workflow - communicating results and zipping files
[11:09:38.360989 INFO] Workflow complete

```

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#246
