### ISSUE TITLE
DView crashes on Ubuntu

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2803]
Stack trace

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff68920f7 in wxDataViewCtrl::OnInternalIdle() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_adv-3.0.so.0
(gdb) bt
#0  0x00007ffff68920f7 in wxDataViewCtrl::OnInternalIdle() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_adv-3.0.so.0
#1  0x00007ffff7375eb9 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#2  0x00007ffff7375f08 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#3  0x00007ffff7375f08 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#4  0x00007ffff7375f08 in wxWindowBase::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#5  0x00007ffff72615af in wxFrame::SendIdleEvents(wxIdleEvent&) ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#6  0x00007ffff7296dbd in wxAppBase::ProcessIdle() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#7  0x00007ffff71ec90e in wxApp::DoIdle() ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#8  0x00007ffff71eca13 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0
#9  0x00007ffff3acece5 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff3acf048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff3acf30a in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---

```

**Comment by evanweaver** [comment]
This issue was moved to NREL/wex#57
