### ISSUE TITLE
SketchUp RuntimeError: bad_weak_ptr

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3537]
I've experienced the following error in the OS 2.6.0 and 2.8.0 SketchUp plugin with SketchUp 2018. The error occurs after importing a DXF into SU and *before* creating OpenStudio geometry.

[SketchUp 2018.skp.txt](https://github.com/NREL/OpenStudio/files/3184188/SketchUp.2018.skp.txt)

```
Error: #<RuntimeError: bad_weak_ptr>
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/RenderingColor.rb:197:in `rebuildInspectorGadget'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/RenderingColor.rb:197:in `update_entity'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:173:in `draw_entity'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:944:in `block in attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `each'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `each_with_index'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:942:in `attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:227:in `attach_openstudio_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:177:in `open_openstudio'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:142:in `new_from_path'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/ModelManager.rb:117:in `new_from_skp_model'
C:/openstudio-2.8.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/observers/AppObserver.rb:63:in `onOpenModel'
```

**Comment by macumber** [comment]
Thanks @MatthewSteen.  How are you importing the DXF, through regular SketchUp import?  Are you able to share the DXF privately?

**Comment by MatthewSteen** [comment]
@macumber yes, I imported through SU. Here's the file. 

[218252-00_SCA_Arch_R18_Central - Sheet - A-111 - OVERALL FLOOR PLAN.dxf.txt](https://github.com/NREL/OpenStudio/files/3192724/218252-00_SCA_Arch_R18_Central.-.Sheet.-.A-111.-.OVERALL.FLOOR.PLAN.dxf.txt)

**Comment by jmarrec** [comment]
Should be transferred to https://github.com/NREL/openstudio-sketchup-plugin I suppose.
