### ISSUE TITLE
OpenStudio CLI for Revit 2020 not working on Windows 10 laptop.

### ISSUE THREAD

**Issue by mcneillj** [NREL/OpenStudio#3883]
Issue overview
--------------

Openstudio CLI for Revit 2020 does not produce an output in Revit 2020.  It seems as if Revit is not able to successfully call the OpenStudio CLI, as the failure completes in 1-3 seconds.  I'm trying to figure out whether the issue is my Windows, Revit, Openstudio configuration, or a bug with Revit or OpenStudio.  I've narrowed it down to most likely being with the Openstudio CLI for Revit 2020.

This issue occurs on a Windows Surface Laptop 3, but does not occur on a Mac Laptop running Windows 10 in Parallels.

## Current Behavior
I've tested the OpenStudio CLI for Revit 2020 by running basic commands on the command prompt.  I've noticed that a response is returned when running "openstudio.exe -h".  No response is provided when running "openstudio.exe run -h".

## Expected Behavior
I would expect that I would be able to make basic calls to the command line with the CLI and get responses.  I am able to do this on a Mac running Windows in Parallels, but not on a Windows laptop.

## Steps to Reproduce

1.  Install Revit 2020.2 for Windows 64
2.  Run "C:\Program Files\NREL\OpenStudio CLI For Revit 2020\bin\openstudio.exe run -h" in a Windows Command Prompt.
3. No response is provided on the command line after running the command.  Response is blank and advances to a new line.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 Enterprise Version 1909 OS Build 18363.657

 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio CLI for Revit 2020 -> OS 2.8.0/2.8.1

### Possible Solution
The appropriate response to the command line call (C:\Program Files\NREL\OpenStudio CLI For Revit 2020\bin\openstudio.exe run -h) is seen on a Mac OS with Parallels running Windows 10 Home, Version 1909, OS Build 18363.418.  I can also successfully use Revit Systems Analysis on this machine (i.e. it produces an EnergyPlus output file that is viewable within the Revit interface).  This makes me wonder if the issue is related to an issue caused by a Windows Update.

### Context

I'm trying to use Revit Systems Analysis for Revit 2020.2.1.  I currently don't get any output running the default workflow and measures.

**Comment by tijcolem** [comment]
Hi James, 

Thanks for the detailed issue report. A couple of questions and things you can try out. 

1 )  Did openstudio CLI previously work on that machine?  Did you upgrade Windows and then it stopped working? 

2 ) If you recently upgraded Windows, can you rule out any strange permission errors and try running the CLI using Administrator account? You can do that by launching a Command Prompt in the Windows Start menu and run as Administrator.  Then you can run CLI from within that shell. 

3 ) You can also try running a with these flags and see what the output is. 
`openstudio --verbose --debug run`

**Comment by mcneillj** [comment]
@tijcolem 

1) From the best of my memory it originally worked on that laptop.  I believe it stopped working after not using it for several weeks.  That’s why I thought it might be a windows Update.  Originally I thought it might be a conflict with other software or settings changes, so I did a full and reinstalled Windows.   It still does not work after that.

2) I think I tried that in all my testing, but will try again

3) I tried with the verbose flag, but not with the debug flag.  Will give that a try.

FYI - I’ll be out of internet service for 2 weeks while traveling.  I’ll test #2 and #3 when I return.

**Comment by mcneillj** [comment]
Output on the Windows 10 machine. 

![image](https://user-images.githubusercontent.com/4923674/76664401-7a752a80-6541-11ea-9917-35c251c69abc.png)

**Comment by mcneillj** [comment]
On Mac OS X I get the following response.
![image](https://user-images.githubusercontent.com/4923674/76664535-f8d1cc80-6541-11ea-9091-230bb86d8b1d.png)

**Comment by lainsworth8801** [comment]
Hi James, sorry about the late response. I believe this has something to do with specific windows built config. I recommend you install the latest openstudio as we confirmed that this issue is resolved with the latest windows build.

<img width="1030" alt="Screen Shot 2020-05-29 at 2 17 15 PM" src="https://user-images.githubusercontent.com/49968203/83834208-f4cdca80-a6aa-11ea-81a6-b90898627070.png">

Also, according to this [link](https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/sfdcarticles/sfdcarticles/Family-Corruption-in-Revit-2020-2.html) Revit 2020.2 hot fix has some known issue that required updates. 

I've run the latest OpenStudio cli tool for both Revit 2020 and 2021 and it works fine on my end.

Please let me know if you have further questions.

**Comment by GianfraG** [comment]
Hi,
I have the same problem. Have you found a solution?

**Comment by lainsworth8801** [comment]
Hi @GianfraG thanks for the issue report! We believe this issue is related to a specific windows 10 image. The first step I would recommend is to update your existing windows build and install the latest OpenStudio CLI package. If you are already on the latest windows build and OpenStudio CLI and issue still persists, please attach a copy of error log for further touble-shooting.

We did run into a similar [issue](https://github.com/NREL/OpenStudio/issues/3991) and it is under investigation.

Please let me know if you have any questions or update. Thanks again for your time.

**Comment by GianfraG** [comment]
Thank you very much @lainsworth8801. 
I updated Windows 10  [Versione 10.0.18363.900] and I copied the "bin" and "EnergyPlus" folders of OpenStudio 3.0.0 in the "OpenStudio CLI for Revit 2021" folder. 
Seems there are no problems now.

**Comment by mcneillj** [comment]
Thanks @lainsworth8801.  I'll give the latest versions a try and report if my issue is solved.

**Comment by tijcolem** [comment]
Hi @mcneillj  Could you let us know if the windows update fixed your issue? If so I will close this ticket.

**Comment by tijcolem** [comment]
Closing this ticket as the recommended solution is to upgrade Windows >= Version 10.0.18363.900

**Comment by ForInfinity** [comment]
Same Error and Symptoms. I've tried to replace bin and EnergyPlus folder of revit plugin, but there's now another error:
```
[22:05:05.485824 ERROR] Found error in state 'os_measures' with message [":/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with message Runner error :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with undefined method `setDesignWaterOutletTemperature' for #<OpenStudio::Model::BoilerHotWater:0x000001ee59b6b860>, C:/PROGRA~1/NREL/OPENST~1/measures/gbxml_hvac_import/resources/condenser_loop.rb:144:in `add_boiler'\nC:/PROGRA~1/NREL/OPENST~1/measures/gbxml_hvac_import/resources/condenser_loop.rb:38:in `build'\nC:/PROGRA~1/NREL/OPENST~1/measures/gbxml_hvac_import/resources/model_manager.rb:86:in `map'\nC:/PROGRA~1/NREL/OPENST~1/measures/gbxml_hvac_import/resources/model_manager.rb:86:in `build'\nC:/PROGRA~1/NREL/OPENST~1/measures/gbxml_hvac_import/measure.rb:69:in `run'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:510:in `apply_measure'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:973:in `execute'\n:/openstudio_cli.rb:763:in `execute'\n:/openstudio_cli.rb:1757:in `<main>'\neval:149:in `eval'\neval:149:in `require_embedded_absolute'\neval:123:in `block in require'\neval:117:in `each'\neval:117:in `require'\neval:3:in `<main>' in :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:538:in `rescue in apply_measure'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:498:in `apply_measure'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:973:in `execute'\n:/openstudio_cli.rb:763:in `execute'\n:/openstudio_cli.rb:1757:in `<main>'\neval:149:in `eval'\neval:149:in `require_embedded_absolute'\neval:123:in `block in require'\neval:117:in `each'\neval:117:in `require'\neval:3:in `<main>'::/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:647:in `rescue in apply_measure'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:305:in `apply_measure'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_os_measures.rb:70:in `perform'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:973:in `execute'\n:/openstudio_cli.rb:763:in `execute'\n:/openstudio_cli.rb:1757:in `<main>'\neval:149:in `eval'\neval:149:in `require_embedded_absolute'\neval:123:in `block in require'\neval:117:in `each'\neval:117:in `require'\neval:3:in `<main>'"]}
```

It seems like the method `setDesignWaterOutletTemperature` is deprecated or there's a breaking change between v 2.8.1 and v 3.0.0?
