### ISSUE TITLE
Error running Measure Manager on OSX. 

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#3930]
When running the 3.0.0-rc1 on mac only using the measure manager, the following error occurs. 

/Applications/OpenStudio-3.0.0-rc1/bin/openstudio --verbose measure -r nrel_published/AddCostPerAreaToConstruction/
I, [2020-03-26T16:47:49.752550 #45638] INFO -- : CLI Parsed Inputs: [“--verbose”] “measure” [“-r”, “nrel_published/AddCostPerAreaToConstruction/“]
D, [2020-03-26T16:47:49.754057 #45638] DEBUG -- : Main arguments are [“--verbose”]
D, [2020-03-26T16:47:49.754102 #45638] DEBUG -- : Sub-command is measure
D, [2020-03-26T16:47:49.754139 #45638] DEBUG -- : Sub-arguments are [“-r”, “nrel_published/AddCostPerAreaToConstruction/“]
D, [2020-03-26T16:47:49.754162 #45638] DEBUG -- : Parsing main_args [“--verbose”]
D, [2020-03-26T16:47:50.137716 #45638] DEBUG -- : Adding dependency on openstudio-extension ‘~> 0.2.1’
D, [2020-03-26T16:47:50.137799 #45638] DEBUG -- : Adding dependency on jaro_winkler ‘~> 1.5.4’
D, [2020-03-26T16:47:50.137835 #45638] DEBUG -- : Adding dependency on pycall ‘~> 1.2.1’
D, [2020-03-26T16:47:50.137868 #45638] DEBUG -- : Adding dependency on ansi ‘~> 1.5.0’
D, [2020-03-26T16:47:50.137898 #45638] DEBUG -- : Adding dependency on ast ‘~> 2.4.0’
D, [2020-03-26T16:47:50.137926 #45638] DEBUG -- : Adding dependency on builder ‘~> 3.2.4’
D, [2020-03-26T16:47:50.137955 #45638] DEBUG -- : Adding dependency on bundler ‘~> 2.1.0’
D, [2020-03-26T16:47:50.137984 #45638] DEBUG -- : Adding dependency on docile ‘~> 1.3.2’
D, [2020-03-26T16:47:50.138012 #45638] DEBUG -- : Adding dependency on git ‘~> 1.6.0’
D, [2020-03-26T16:47:50.138040 #45638] DEBUG -- : Adding dependency on minitest ‘~> 5.14.0’
D, [2020-03-26T16:47:50.138069 #45638] DEBUG -- : Adding dependency on minitest-reporters ‘~> 1.4.2’
D, [2020-03-26T16:47:50.138520 #45638] DEBUG -- : Adding dependency on openstudio-standards ‘~> 0.2.11.rc1’
D, [2020-03-26T16:47:50.138551 #45638] DEBUG -- : Adding dependency on openstudio-workflow ‘~> 2.0.0’
D, [2020-03-26T16:47:50.138580 #45638] DEBUG -- : Adding dependency on openstudio_measure_tester ‘~> 0.2.1’
D, [2020-03-26T16:47:50.138609 #45638] DEBUG -- : Adding dependency on parallel ‘~> 1.19.1’
D, [2020-03-26T16:47:50.138637 #45638] DEBUG -- : Adding dependency on parser ‘~> 2.7.0.5’
D, [2020-03-26T16:47:50.138666 #45638] DEBUG -- : Adding dependency on rainbow ‘~> 3.0.0’
D, [2020-03-26T16:47:50.140603 #45638] DEBUG -- : Adding dependency on rake ‘~> 13.0.1’
D, [2020-03-26T16:47:50.140673 #45638] DEBUG -- : Adding dependency on rchardet ‘~> 1.8.0’
D, [2020-03-26T16:47:50.140706 #45638] DEBUG -- : Adding dependency on rexml ‘~> 3.2.4’
D, [2020-03-26T16:47:50.140736 #45638] DEBUG -- : Adding dependency on rubocop ‘~> 0.80.1’
D, [2020-03-26T16:47:50.140787 #45638] DEBUG -- : Adding dependency on rubocop-checkstyle_formatter ‘~> 0.4.0’
D, [2020-03-26T16:47:50.140819 #45638] DEBUG -- : Adding dependency on ruby-progressbar ‘~> 1.10.1’
D, [2020-03-26T16:47:50.140859 #45638] DEBUG -- : Adding dependency on simplecov ‘~> 0.18.5’
D, [2020-03-26T16:47:50.140890 #45638] DEBUG -- : Adding dependency on simplecov-html ‘~> 0.12.2’
D, [2020-03-26T16:47:50.140929 #45638] DEBUG -- : Adding dependency on unicode-display_width ‘~> 1.6.1’
D, [2020-03-26T16:47:50.163815 #45638] DEBUG -- : Processing 26 activation requests
D, [2020-03-26T16:47:50.163974 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/parallel-1.19.1.gemspec
D, [2020-03-26T16:47:50.164676 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/simplecov-html-0.12.2.gemspec
D, [2020-03-26T16:47:50.164845 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/docile-1.3.2.gemspec
D, [2020-03-26T16:47:50.165479 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/simplecov-0.18.5.gemspec
D, [2020-03-26T16:47:50.165651 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/unicode-display_width-1.6.1.gemspec
D, [2020-03-26T16:47:50.166227 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/ruby-progressbar-1.10.1.gemspec
D, [2020-03-26T16:47:50.166795 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rexml-3.2.4.gemspec
D, [2020-03-26T16:47:50.166937 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rainbow-3.0.0.gemspec
D, [2020-03-26T16:47:50.167480 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/ast-2.4.0.gemspec
D, [2020-03-26T16:47:50.167623 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/parser-2.7.0.5.gemspec
D, [2020-03-26T16:47:50.168154 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/bundler/specifications/jaro_winkler-1.5.4.gemspec
D, [2020-03-26T16:47:50.169126 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rubocop-0.80.1.gemspec
D, [2020-03-26T16:47:50.169353 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rubocop-checkstyle_formatter-0.4.0.gemspec
D, [2020-03-26T16:47:50.169736 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rake-13.0.1.gemspec
D, [2020-03-26T16:47:50.169892 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/builder-3.2.4.gemspec
D, [2020-03-26T16:47:50.171518 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/ansi-1.5.0.gemspec
D, [2020-03-26T16:47:50.171696 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/minitest-5.14.0.gemspec
D, [2020-03-26T16:47:50.171864 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/minitest-reporters-1.4.2.gemspec
D, [2020-03-26T16:47:50.172073 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/rchardet-1.8.0.gemspec
D, [2020-03-26T16:47:50.172228 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/git-1.6.0.gemspec
D, [2020-03-26T16:47:50.172412 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/openstudio_measure_tester-0.2.1.gemspec
D, [2020-03-26T16:47:50.172634 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/openstudio-workflow-2.0.0.gemspec
D, [2020-03-26T16:47:50.172802 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/bundler-2.1.0.gemspec
D, [2020-03-26T16:47:50.172960 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/bundler/specifications/openstudio-extension-0.2.1.gemspec
D, [2020-03-26T16:47:50.173192 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/bundler/specifications/pycall-1.2.1.gemspec
D, [2020-03-26T16:47:50.173449 #45638] DEBUG -- : Activating gem :/ruby/2.5.0/specifications/openstudio-standards-0.2.11.rc1.gemspec
D, [2020-03-26T16:47:50.173584 #45638] DEBUG -- : Invoking command class: Measure [“-r”, “nrel_published/AddCostPerAreaToConstruction/“]
I, [2020-03-26T16:47:50.173610 #45638] INFO -- : Measure, sub_argv = [“-r”, “nrel_published/AddCostPerAreaToConstruction/“]
D, [2020-03-26T16:47:50.438115 #45638] DEBUG -- : Directory to examine is nrel_published/AddCostPerAreaToConstruction/
D, [2020-03-26T16:47:50.438183 #45638] DEBUG -- : Remaining args are [“-r”]
D, [2020-03-26T16:47:50.438789 #45638] DEBUG -- : Measure command: [] {:update=>false, :compute_arguments=>nil, :run_tests=>true}
D, [2020-03-26T16:47:50.438889 #45638] DEBUG -- : Directory to examine is /Users/tijcolem/git/OpenStudio-measures/nrel_published/AddCostPerAreaToConstruction
D, [2020-03-26T16:47:50.438915 #45638] DEBUG -- : Minitest arguments are ‘[]’
Ignoring executable-hooks-1.6.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.0
Ignoring ffi-1.11.1 because its extensions are not built. Try: gem pristine ffi --version 1.11.1
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4
Ignoring pycall-1.2.1 because its extensions are not built. Try: gem pristine pycall --version 1.2.1
Ignoring unf_ext-0.0.7.6 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.6
Base dir is /Users/tijcolem/git/OpenStudio-measures/nrel_published/AddCostPerAreaToConstruction
 ========================= Starting Run for Rubocop ================================
Current directory is /Users/tijcolem/git/OpenStudio-measures/nrel_published/AddCostPerAreaToConstruction
Test results will be stored in: /Users/tijcolem/git/OpenStudio-measures/nrel_published/AddCostPerAreaToConstruction/test_results
Error executing argv: []
Error: undefined method `read_nonblock’ for #<TCPSocket:(closed)> in :/ruby/2.5.0/net/protocol.rb:175:in `rbuf_fill’
:/ruby/2.5.0/net/protocol.rb:157:in `readuntil’
:/ruby/2.5.0/net/protocol.rb:167:in `readline’
:/ruby/2.5.0/net/http/response.rb:40:in `read_status_line’
:/ruby/2.5.0/net/http/response.rb:29:in `read_new’
:/ruby/2.5.0/net/http.rb:1499:in `block in transport_request’
:/ruby/2.5.0/net/http.rb:1496:in `catch’
:/ruby/2.5.0/net/http.rb:1496:in `transport_request’
:/ruby/2.5.0/net/http.rb:1469:in `request’
:/ruby/2.5.0/net/http.rb:1462:in `block in request’
:/ruby/2.5.0/net/http.rb:912:in `start’
:/ruby/2.5.0/net/http.rb:1460:in `request’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/remote_config.rb:49:in `block in request’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/remote_config.rb:63:in `generate_request’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/remote_config.rb:47:in `request’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/remote_config.rb:21:in `file’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader.rb:40:in `load_file’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader_resolver.rb:143:in `block in base_configs’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader_resolver.rb:142:in `map’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader_resolver.rb:142:in `base_configs’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader_resolver.rb:22:in `resolve_inheritance’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader.rb:50:in `load_file’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_loader.rb:86:in `configuration_from_file’
:/ruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop/config_store.rb:44:in `for’
:/ruby/2.5.0/gems/openstudio_measure_tester-0.2.1/lib/openstudio_measure_tester/runner.rb:150:in `run_rubocop’
:/ruby/2.5.0/gems/openstudio_measure_tester-0.2.1/lib/openstudio_measure_tester/runner.rb:329:in `run_all’
:/openstudio_cli.rb:1355:in `execute’
:/openstudio_cli.rb:763:in `execute’
:/openstudio_cli.rb:1757:in `<main>'
eval:137:in `eval’
eval:137:in `require_embedded_absolute’
eval:110:in `block in require’
eval:104:in `each’
eval:104:in `require’
eval:3:in <main>'

```

**Comment by tijcolem** [comment]
Fixed in #3931
