### ISSUE TITLE
Using IRB to call OpenStudio throws an error. Cannot find openstudio.so

### ISSUE THREAD

**Issue by luisclv** [NREL/OpenStudio#4357]
Issue overview
--------------
Normally, requiring the `openstudio.rb` file located in `.\openstudio-3.2.0\Ruby\` loads the OpenStudio environment in a terminal or a Ruby script. However, with this update it fails. I have tested this in 3 different computers, including one with a fresh install of 3.2.0 and 3.1.0.

## Current Behavior
```ruby
irb(main):001:0> require 'C:\openstudio-3.1.0\Ruby\openstudio.rb'
=> true
irb(main):002:0> require 'C:\openstudio-3.2.0\Ruby\openstudio.rb'
Traceback (most recent call last):
        6: from C:/Ruby25-x64/bin/irb.cmd:19:in `<main>'
        5: from (irb):2
        4: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from C:/openstudio-3.2.0/Ruby/openstudio.rb:55:in `<top (required)>'
        1: from C:/openstudio-3.2.0/Ruby/openstudio.rb:55:in `require_relative'
LoadError (126: The specified module could not be found.   - C:/openstudio-3.2.0/Ruby/openstudio.so)
```
## Expected Behavior
```ruby
irb(main):001:0> require 'C:\openstudio-3.1.0\Ruby\openstudio.rb'
=> true
irb(main):002:0> require 'C:\openstudio-3.2.0\Ruby\openstudio.rb'
=> true
```

## Steps to Reproduce
```ruby
irb(main):001:0> require 'C:\openstudio-3.2.0\Ruby\openstudio.rb'
```

## Possible Solution

As far I can tell, both files are exactly the same, and the directories also contain `openstudio.so`.

## Details

This is what my 3.2.0 directory looks like:
```
C:\openstudio-3.2.0\Ruby>dir
 Volume in drive C has no label.
 Volume Serial Number is XXXX-XXXX

 Directory of C:\openstudio-3.2.0\Ruby

05/09/2021  02:10 PM    <DIR>          .
05/09/2021  02:10 PM    <DIR>          ..
11/30/2020  02:22 PM           309,128 concrt140.dll
04/22/2021  01:04 PM             1,489 Gemfile
04/22/2021  01:04 PM             3,553 Gemfile.lock
05/03/2021  10:50 PM            20,111 measure_manager.rb
05/03/2021  10:50 PM            13,496 measure_manager_server.rb
11/30/2020  02:22 PM           585,096 msvcp140.dll
11/30/2020  02:22 PM            23,944 msvcp140_1.dll
11/30/2020  02:22 PM           186,248 msvcp140_2.dll
11/30/2020  02:22 PM            20,360 msvcp140_codecvt_ids.dll
05/09/2021  02:10 PM    <DIR>          openstudio
04/22/2021  01:04 PM             1,685 openstudio-gems.gemspec
05/03/2021  10:50 PM             3,405 openstudio.rb
05/04/2021  01:09 AM        73,653,760 openstudio.so
05/03/2021  10:50 PM            57,769 openstudio_cli.rb
11/30/2020  02:22 PM            94,088 vcruntime140.dll
11/30/2020  02:22 PM            36,744 vcruntime140_1.dll
              15 File(s)     75,010,876 bytes
               3 Dir(s)  465,290,989,568 bytes free

C:\openstudio-3.2.0\Ruby>irb
irb(main):001:0> Dir.entries(".")
=> [".", "..", "concrt140.dll", "Gemfile", "Gemfile.lock", "measure_manager.rb", "measure_manager_server.rb", "msvcp140.dll", "msvcp140_1.dll", "msvcp140_2.dll", "msvcp140_codecvt_ids.dll", 
"openstudio", "openstudio-gems.gemspec", "openstudio.rb", "openstudio.so", "openstudio_cli.rb", "vcruntime140.dll", "vcruntime140_1.dll"]
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 Pro v2004 19041.985
 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio 3.2.0

### Context
I am trying to use the command line and Ruby scripts on my models, which is a normal workflow for previous versions.

**Comment by eringold** [comment]
I think your problem is Ruby25-x64. OS v3.2.0 requires Ruby 2.7.2: https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Version-Compatibility-Matrix

**Comment by luisclv** [comment]
Pff, I knew it would be something simple! Thanks!
