### ISSUE TITLE
`json-schema` gem causes "cannot load such file" error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4870]
Issue overview
--------------
I'm trying to use the `json-schema` gem bundled in the CLI and it doesn't work.

Here is a quick way to reproduce it. (Obviously in our code, we are actually supplying a path to a json schema, but this is enough to demonstrate the error.)

```
openstudio -e "require 'json-schema'; JSON::Validator.validate('foo', 'bar')"
Error executing argv: ["-e", "require 'json-schema'; JSON::Validator.validate('foo', 'bar')"]
Error: cannot load such file -- unicode_normalize/normalize.rb in :/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:582:in `unicode_normalize'
:/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:582:in `normalize_component'
:/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:895:in `normalized_scheme'
:/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2160:in `normalize'
:/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:2184:in `normalize!'
:/ruby/2.7.0/gems/addressable-2.8.4/lib/addressable/uri.rb:311:in `convert_path'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/util/uri.rb:54:in `file_uri'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/util/uri.rb:18:in `normalized_uri'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:542:in `rescue in initialize_schema'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:532:in `initialize_schema'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:53:in `block in initialize'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:53:in `synchronize'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:53:in `initialize'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:261:in `new'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:261:in `validate!'
:/ruby/2.7.0/gems/json-schema-2.7.0/lib/json-schema/validator.rb:246:in `validate'
eval:48:in `<main>'
:/openstudio_cli.rb:790:in `eval'
:/openstudio_cli.rb:790:in `block in execute'
:/openstudio_cli.rb:788:in `each'
:/openstudio_cli.rb:788:in `execute'
:/openstudio_cli.rb:1984:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Ubuntu 20.04
 - OpenStudio 3.6.0-rc2

### Context
In our [OpenStudio-ERI project](https://github.com/NREL/OpenStudio-ERI), we are writing a JSON output file and wanting to validate it against a JSON schema provided by RESNET.

**Comment by shorowit** [comment]
@tijcolem Yes, I can confirm that it worked in OpenStudio 3.5.1.
