### ISSUE TITLE
Add `json_schemer` gem

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4969]
Enhancement Request
--------------
OpenStudio includes the `json-schema` gem, but it is barely maintained and [many users recommend switching to `json_schemer` gem](https://github.com/voxpupuli/json-schema/issues/423#issuecomment-634811990). Not only is the `json_schemer` gem well maintained, but it supports newer drafts of the JSON schema that are heavily utilized these days. The `json-schema` gem has no current progress towards supporting newer drafts of the schema.

For DOE's Home Energy Score project, we are unable to use the current `json-schema` gem because it doesn't support JSON Schema draft-07. This means that we can't validate JSON files submitted and has occasionally led to issues.

(Perhaps OpenStudio should consider replacing the `json-schema` gem, but that would be a breaking change.)

**Comment by jmarrec** [comment]
No problem. This is a pure ruby gem, no native ext, so we shouldn't need any patching because MSVC doesn't support C99 etc.

@wenyikuang Do you want to take this one?

**Comment by jmarrec** [comment]
Added the PR at https://github.com/NREL/openstudio-gems/pull/64

**Comment by wenyikuang** [comment]
> No problem. This is a pure ruby gem, no native ext, so we shouldn't need any patching because MSVC doesn't support C99 etc.
> 
> @wenyikuang Do you want to take this one?

Sure, let me take a look.

**Comment by jmarrec** [comment]
This works: `openstudio -e "/[\p{Alnum}]/"`, this doesn't `openstudio -e "/[\p{Han}]/"`

**Comment by jmarrec** [comment]
https://github.com/davishmcclurg/json_schemer/blob/6c88530c594a953a11061c6abf642e451b1ad522/lib/json_schemer/format/hostname.rb#L36

**Comment by jmarrec** [comment]
I realize that the conan-openstudio-ruby test_package works fine. Which made me realize this is a regression that dates to when we added python measures and made the CLI non statically linked to ruby

```
$ /usr/local/openstudio-3.4.0/bin/openstudio -e "puts /[\p{Han}]/"
(?-mix:[\p{Han}])
$ /usr/local/openstudio-3.5.0/bin/openstudio -e "puts /[\p{Han}]/"
Error executing argv: ["-e", "puts /[\\p{Han}]/"]
Error: eval:48: invalid character property name {Han}: /[\p{Han}]/ in :/openstudio_cli.rb:777:in `eval'
:/openstudio_cli.rb:777:in `block in execute'
:/openstudio_cli.rb:775:in `each'
:/openstudio_cli.rb:775:in `execute'
:/openstudio_cli.rb:1973:in `<main>'
eval:188:in `eval'
eval:188:in `require_embedded_absolute'
eval:173:in `block in require_embedded'
eval:167:in `each'
eval:167:in `require_embedded'
eval:126:in `require'
eval:3:in `<main>'
```

**Comment by jmarrec** [comment]
With ruby3 I'm having an issue due to this gem on windows.

It depends on simpleidn, which depends on unf_ext, which is a native C++ extension. And it bakes some directives into the unf_ext.lib such as `/FAILIFMISMATCH:RuntimeLibrary=MD_DynamicRelease`. Meaning I can't link to it when I build OS SDK as Debug. Cause of https://github.com/NREL/openstudio-gems/issues/72

**Comment by jmarrec** [comment]
> No problem. This is a pure ruby gem, no native ext, so we shouldn't need any patching because MSVC doesn't support C99 etc.

That couldn't have been more wrong :)

**Comment by DavidGoldwasser** [comment]
@jmarrec what do you think about this in 3.9? Is there a path to do that?

**Comment by shorowit** [comment]
If we went the python route, which would _probably_ work fine for our use case, I think the library we'd want added to OS is [jsonschema](https://pypi.org/project/jsonschema/).
