### ISSUE TITLE
Make sure that Python measure tests work out of the box on clean OpenStudio install

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4992]
Either change sample measure test to use unittest or add Pytest to OpenStudio's Python environment.

**Comment by rajeee** [comment]
Looks like this should have been fixed through https://github.com/NREL/OpenStudio/pull/5008 but I am still getting errors on Openstudio version: 3.8.0+f953b6fcaf

>openstudio [test_model_measure.py](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/bcl/templates/ModelMeasure/tests/test_model_measure.py)

<details>
<summary>Traceback</summary>

Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/radhikar/Documents/OpenStudio/src/utilities/bcl/templates/ModelMeasure/tests/test_model_measure.py", line 150, in <module>
    pytest.main()
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/config/__init__.py", line 155, in main
    config = _prepareconfig(args, plugins)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/config/__init__.py", line 337, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
    config = yield
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/config/__init__.py", line 1143, in pytest_cmdline_parse
    self.parse(args)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/config/__init__.py", line 1492, in parse
    self._preparse(args, addopts=addopts)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/config/__init__.py", line 1379, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pluggy/_manager.py", line 421, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/_pytest/assertion/rewrite.py", line 178, in exec_module
    exec(co, module.__dict__)
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/pytest_cov/plugin.py", line 9, in <module>
    import coverage
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/coverage/__init__.py", line 24, in <module>
    from coverage.control import (
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/coverage/control.py", line 28, in <module>
    from coverage.collector import Collector, HAS_CTRACER
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/coverage/collector.py", line 19, in <module>
    from coverage.data import CoverageData
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/coverage/data.py", line 24, in <module>
    from coverage.sqldata import CoverageData
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/coverage/sqldata.py", line 16, in <module>
    import sqlite3
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/lib-dynload/_sqlite3.cpython-38-darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: <9F88F376-4444-3BC2-BD26-89AD0EF1CCEE> /Applications/OpenStudio-3.8.0/EnergyPlus/python_standard_lib/lib-dynload/_sqlite3.cpython-38-darwin.so
  Expected in:     <2EF69864-7D8D-3BA6-BBA3-46A6CDC7B1B9> /usr/lib/libsqlite3.dylib
Failed to execute '/Users/radhikar/Documents/OpenStudio/src/utilities/bcl/templates/ModelMeasure/tests/test_model_measure.py'
 

</details>

**Comment by jmarrec** [comment]
This isn't the same issue at all. This issue should be close. I'm transfering it to #5217 @rajeee

**Comment by DavidGoldwasser** [comment]
I may need to re-open this but I'm going to do some testing first, but it seems I need to use my own Python and not the Python that comes with OpenStudio. as a result I have to do `python mytest.py` and not `openstudio pytest.py` or `openstudio measure --run_tests`

**Comment by jmarrec** [comment]
What a teaser :)

Can you say more?

```
openstudio measure new \
  --type ModelMeasure --language Python \
  --class-name TestPython \
  --taxonomy-tag "HVAC.Ventilation" \
  --name "Test Python" \
  --description "This measure should be deleted" \
  --modeler-description "I'm just testing something." \
  ./test_python

cd test_python
openstudio measure -r .
```

```
┌────────────────────────────────────────────────────────────────────────────────┐
│                             Starting Python Tests                              │
└────────────────────────────────────────────────────────────────────────────────┘
runPytestCmd=
import pytest

pytest.main([
  "--junit-xml=/home/julien/OpenStudio/Measures/test_python/test_results/pytest/junit.xml",
  "--cov=/home/julien/OpenStudio/Measures/test_python",
  "--cov-report=term-missing",
  "--cov-report=json:/home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.json",
  "--cov-report=lcov:/home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.lcov",
  "--cov-report=html:/home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage_html",
  "--cov-report=xml:/home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.xml",
  "-o", "junit_family=legacy",
  "/home/julien/OpenStudio/Measures/test_python",
])

=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.12.2, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/julien/OpenStudio/Measures/test_python
plugins: cov-5.0.0
collected 3 items                                                                                                                                                                                          

tests/test_test_python.py ...                                                                                                                                                                        [100%]

============================================================================================= warnings summary =============================================================================================
.:0
  :0: PytestCollectionWarning: cannot collect test class 'TestPython' because it has a __init__ constructor (from: tests/test_test_python.py)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------------------------------------------------------ generated xml file: /home/julien/OpenStudio/Measures/test_python/test_results/pytest/junit.xml ------------------------------------------------------

---------- coverage: platform linux, python 3.12.2-final-0 -----------
Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
measure.py                     31      4    87%   25, 33, 43, 69
tests/test_test_python.py      75      4    95%   146-150
---------------------------------------------------------
TOTAL                         106      8    92%
Coverage HTML written to dir /home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage_html
Coverage XML written to file /home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.xml
Coverage JSON written to file /home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.json
Coverage LCOV written to file /home/julien/OpenStudio/Measures/test_python/test_results/pytest/python_coverage.lcov

```
