### ISSUE TITLE
If a reporting measure throws an error (runner.registerError("ERROR TEST"); return false), openstudio doesn't seem to gracefully handle it:

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5020]
Issue overview
--------------

## Current Behavior

If a reporting measure throws an error (`runner.registerError("ERROR TEST"); return false`), openstudio doesn't seem to gracefully handle it:

```
    terminate called after throwing an instance of 'std::runtime_error'
       what():  Measure ReportSimulationOutput reported an error with [ERROR TEST]
   Aborted (core dumped)
 ```

## Expected Behavior

Should gracefully handle it

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0-rc2

### Context

- #5016

**Comment by jmarrec** [comment]
tested with a measure that has a runner.registerError("An Error"):

```shell
(py39)julien@compact_osw$ $os_build/Products/openstudio run --show-stdout --style-stdout -w compact_ruby_only.osw

┌────────────────────────────────────────────────────────────────────────────────┐
│                         Starting State Initialization                          │
└────────────────────────────────────────────────────────────────────────────────┘
[openstudio.EpwFile] <0> Header start day of the week and actual start day of the week do not match in EPW file '/home/julien/Software/Others/OS-build/resources/Examples/compact_osw/files/srrl_2013_amy.epw'. Data will be treated as typical (TMY)
#######################Returned from State Initialization#######################

┌────────────────────────────────────────────────────────────────────────────────┐
│                       Starting State OpenStudioMeasures                        │
└────────────────────────────────────────────────────────────────────────────────┘
[openstudio.workflow.OSWorkflow] <1> Found error in state 'OpenStudioMeasures' with message :'Measure IncreaseWallRValue reported an error with [An error]'
Failed to run workflow
  Last Error:
Found error in state 'OpenStudioMeasures' with message :'Measure IncreaseWallRValue reported an error with [An error]'
(py39)julien@compact_osw$ echo $?
1
```

**Comment by wenyikuang** [comment]
I am not sure it's related  or not, that's something I faced when I was trying to fix os-extension-gems issue

In RC1, after you run `bundle exec rake` in openstudio-exetension-gems` it equivilently run:

```
➜  test git:(patch_verbose) ✗ /Applications/OpenStudio-3.7.0-rc1/bin/openstudio --bundle '~/Development/openstudio-extension-gem/Gemfile' --bundle_path '~/Development/openstudio-extension-gem/.bundle/install/' run -w '~/Development/openstudio-extension-gem/spec/test/runner/in.osw'  2>&1 > "~/Development/openstudio-extension-gem/spec/test/runner/in.osw.log"

```

And it will not raise exeception, but if you run the samething in rc2, it will:

```
/Applications/OpenStudio-3.7.0-rc2/bin/openstudio --bundle '~/Development/openstudio-extension-gem/Gemfile' --bundle_path '!/Development/openstudio-extension-gem/.bundle/install/' run -w '~/Development/openstudio-extension-gem/spec/test/runner/in.osw'
```
Raise:

```
[openstudio.WorkflowJSON] <2> Path '/Users/wkuang/Development/openstudio-extension-gem/spec/test/runner/in.osw' is not a WorkflowJSON file
libc++abi: terminating with uncaught exception of type openstudio::Exception: /Users/julien/Software/Others/OpenStudio/src/utilities/filetypes/WorkflowJSON.cpp@72 : Path '/Users/wkuang/Development/openstudio-extension-gem/spec/test/runner/in.osw' is not a WorkflowJSON file
[1]    31649 abort      /Applications/OpenStudio-3.7.0-rc2/bin/openstudio --bundle  --bundle_path  ru
```


And if you make the rc1 to print out the debug information:


```
/Applications/OpenStudio-3.7.0-rc1/bin/openstudio --verbose --bundle '/Users/wkuang/Development/openstudio-extension-gem/Gemfile' --bundle_path '/Users/wkuang/Development/openstudio-extension-gem/.bundle/install/' run -w '/Users/wkuang/Development/openstudio-extension-gem/spec/test/runner/in.osw'
```

It will print:


``` Error executing argv: ["--verbose", "--bundle", "/Users/wkuang/Development/openstudio-extension-gem/Gemfile", "--bundle_path", "/Users/wkuang/Development/openstudio-extension-gem/.bundle/install/", "run", "-w", "/Users/wkuang/Development/openstudio-extension-gem/spec/test/runner/in.osw"]
Error: Could not find racc-1.7.3 in any of the sources in :/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:86:in `block in materialize'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
:/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
:/openstudio_cli.rb:654:in `parse_main_args'
:/openstudio_cli.rb:784:in `execute'
:/openstudio_cli.rb:1987:in `<main>'
eval:193:in `eval'
eval:193:in `require_embedded_absolute'
eval:178:in `block in require_embedded'
eval:172:in `each'
eval:172:in `require_embedded'
eval:131:in `require'
eval:3:in `<main>'

```

In the other word. The racc dependency issue is there for a while. But it doesn't raise the exception (to break the workflow run) in the rc1.

Do we need to update the dependency? 
Is it something will be fixed along together with this issue? (Handle exception gracefully)

**Comment by wenyikuang** [comment]
The minimum test case is if you pass a empty string into the `run -w` then it will crash...


```
➜  build git:(develop) ✗ /Applications/OpenStudio-3.7.0-rc1/bin/openstudio run -w ""
Error executing argv: ["run", "-w", ""]
Error: Is a directory @ io_fread - /Users/wkuang/Development/Openstudio-official/build in eval:405:in `read'
eval:405:in `read'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/adapters/input/local.rb:50:in `initialize'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:138:in `new'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:138:in `initialize'
:/openstudio_cli.rb:1187:in `new'
:/openstudio_cli.rb:1187:in `execute'
:/openstudio_cli.rb:820:in `execute'
:/openstudio_cli.rb:1987:in `<main>'
eval:193:in `eval'
eval:193:in `require_embedded_absolute'
eval:178:in `block in require_embedded'
eval:172:in `each'
eval:172:in `require_embedded'
eval:131:in `require'
eval:3:in `<main>'
➜  build git:(develop) ✗ openstudio run -w ""
[openstudio.WorkflowJSON] <2> Path '' is not a WorkflowJSON file
libc++abi: terminating with uncaught exception of type openstudio::Exception: /Users/julien/Software/Others/OpenStudio/src/utilities/filetypes/WorkflowJSON.cpp@72 : Path '' is not a WorkflowJSON file
[1]    38370 abort      openstudio run -w ""
```
