### ISSUE TITLE
Issue with runner.lastEnergyPlusSqlFile

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5147]
Issue overview
--------------

## Current Behavior

In measure testing:

```ruby
-sqlFile = OpenStudio::SqlFile.new(OpenStudio::Path.new(sql_path(test_name))) # Works
+sqlFile = runner.lastEnergyPlusSqlFile.get # Fails
 hours = sqlFile.hoursSimulated
 refute_empty(hours)
 assert_equal(8760.0, hours.get)
```

```
OpenStudioResults_Test#test_example_model_si:
RuntimeError: Error creating prepared statement: SELECT Value FROM TabularDataWithStrings
                                  WHERE ReportName='InputVerificationandResultsSummary'
                                  AND ReportForString='Entire Facility'
                                  AND TableName='General'
                                  AND RowName='Hours Simulated'
                                  AND Units='hrs' with error code 21, extended code 21, errmsg: bad parameter or other API misuse
    OpenStudioResults_Test.rb:263:in `hoursSimulated'
    OpenStudioResults_Test.rb:263:in `test_example_model_si
```

## Possible Solution

Pretty sure it's because "sql_file.close" is at the end of the measure template...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment]
Yep, it's becaue sql_file.close

This fixes it.

```ruby
    sqlFile = runner.lastEnergyPlusSqlFile.get
    if !sqlFile.connectionOpen
      sqlFile.reopen
    end
```

I'll adjust the templates
