### ISSUE TITLE
`openstudio classic measure -s` is broken (measure manager using classic CLI) in 3.8.0

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5212]
Issue overview
--------------

The measure manager in the classic CLI is broken in 3.8.0

## Current Behavior

```
$ openstudio --version
3.8.0+f953b6fcaf
$ openstudio classic measure -s 8091
┌────────────────────────────────────────────────────────────────────────────────┐
│  The `classic` command is deprecated and will be removed in a future release   │
└────────────────────────────────────────────────────────────────────────────────┘
Error executing argv: ["measure", "-s", "8091"]
Error: cannot load such file -- webrick in eval:182:in `require'
```

## Expected Behavior

It should work.

## Possible Solution

`webrick` gem was removed from the standard library in Ruby 3. So it should be part of the openstudio-gems Gemfile. Or the classic subcommand should be removed.

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

> The following libraries are no longer bundled gems or standard libraries. Install the corresponding gems to use these features.
> sdbm, webrick, net-telnet, xmlrpc

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.8.0

### Context

Found in OpenStudioApplication at https://github.com/openstudiocoalition/OpenStudioApplication/pull/714#issuecomment-2132780927

**Comment by macumber** [comment]
I think even the non-classic CLI has some issues in 3.8.0, it fails to infer measure name for the OpenStudio Results measure.

**Comment by jmarrec** [comment]
@macumber No, that's a combination of:

1. The openstudio-extension gem was gutted down after we moved stuff to the C++ side
2. The OpenStudioApp is using an outdated measure (but I haven't checked if @DavidGoldwasser released an updated one)

The actual error:

```shell
$ cd OpenStudioApplication/src/openstudio_app/Resources/openstudio_results
$ openstudio measure -u .

Failed to infer measure name from /Users/julien/Software/Others/OpenStudioApplication/src/openstudio_app/Resources/openstudio_results/./measure.rb: LoadError: cannot load such file -- openstudio/extension/core/os_lib_schedules
location=["eval:182:in `require'", "eval:182:in `require'", "<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'", "/Users/julien/Software/Others/OpenStudioApplication/src/openstudio_app/Resources/openstudio_results/measure.rb:11:in `<top (required)>'", "eval:8:in `load'", "eval:8:in `<main>'"]

Traceback:
eval:182:in `require'
eval:182:in `require'
<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/julien/Software/Others/OpenStudioApplication/src/openstudio_app/Resources/openstudio_results/measure.rb:11:in `<top (required)>'
eval:8:in `load'
eval:8:in `<main>'
className=
Failed to infer measure name from '/Users/julien/Software/Others/OpenStudioApplication/src/openstudio_app/Resources/openstudio_results/./measure.rb'
```

**Comment by jmarrec** [comment]
Apparently not yet;: https://github.com/NREL/openstudio-common-measures-gem/blob/473f9e7df50014262f21231e524f1510bcfae985/lib/measures/openstudio_results/measure.rb#L11

**Comment by DavidGoldwasser** [comment]
I'll try to get all the measures up to ruby.gems and BCL by the end of the week. My attempt to be productive while at SimBuild last week didn't work.

**Comment by jmarrec** [comment]
@DavidGoldwasser Are you still working on https://github.com/NREL/openstudio-common-measures-gem/pull/169 ?

We'd like for openstudio-results at least to be updated, since the OSApp ships it by default and it breaks users that chose to enable the "classic" CLI.

**Comment by MatthewSteen** [comment]
> Apparently not yet;: https://github.com/NREL/openstudio-common-measures-gem/blob/473f9e7df50014262f21231e524f1510bcfae985/lib/measures/openstudio_results/measure.rb#L11
> 
> But should soon, this PR seem to have it: https://github.com/NREL/openstudio-common-measures-gem/pull/169/files#diff-f17e661c254a9015bada9e2f41b56572513c4d93ba52eebbe12c9c4a46247f93L9

These changes were included in https://github.com/NREL/gbxml-to-openstudio/releases/tag/v1.2.0. 

---

> These gbxml measures seem to be affected too: https://github.com/NREL/gbxml-to-openstudio

Our latest release was tested and works. We (and Autodesk) don't use the `classic` or `measure -s` args, just `openstudio run -w`.

**Comment by DavidGoldwasser** [comment]
@jmarrec plan to have updated measures including OpenStudio Results released and on BCL soon.

**Comment by macumber** [comment]
@MatthewSteen I get this on the `gbxml_import_advanced` measure

```
c:\openstudio-3.8.0\bin\openstudio.exe measure -a C:\test\untitled.osm gbxml_import_advanced
> Failed to infer measure name from C:/repos/gbxml-to-openstudio/measures/gbxml_import_advanced/measure.rb: NoMethodError: undefined method `ancestors' for 0.05:Float
```

I see a similar error when dragging the `gbxml_import_hvac` measure into the 1.8.0 version of the OpenStudio Application.  That one occurs because `gbxml_import_hvac.rb` is not in the resources directory so doesn't get copied over.

**Comment by MatthewSteen** [comment]
@macumber ok, thanks. We haven't experienced this error with the Autodesk workflow, but I will take a look and try to resolve what we can in the gbxml-to-openstudio repo. FYI these measures are not (currently) intended to be used with the OpenStudio Application, hence they're not on the BCL.

**Comment by kbenne** [comment]
@wenyikuang can you look at my [PR](https://github.com/NREL/openstudio-gems/pull/99) to bring in webrick? I think this should address the issue once we pull in the new openstudio-gems to the main openstudio project.
