### ISSUE TITLE
Failed to Infer Measure Name

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio#5215]
When running the openstudio CLI `measure -u` call on a measure, I often get this error: "Failed to infer measure name from '/path/to/measure/measure.rb'".  I get it on Python measures as well as Ruby measures.   This error also ends up in the xml file in an <error> tag. For example: https://github.com/NREL/OpenStudio-workflow-gem/blob/39c84e45f152446a92379a501807e2691dba15ab/spec/files/script_error_osw/measures/IncreaseWallRValue/measure.xml#L4

Measures contains such errors do not get uploaded to the BCL. I don't think they work in the OS apps either.

Ruby code that triggers the error:
https://github.com/NREL/OpenStudio/blob/ba1b94b6542c1f1d4cdcdb775886852b9a82bc4f/ruby/engine/RubyEngine.cpp#L154-L203
Python code that triggers the error:
https://github.com/NREL/OpenStudio/blob/eb043d23f746e8df3b2819ac43eeb19958973e0c/python/engine/PythonEngine.cpp#L286-L310

I'd like to understand better why this error is being triggered...I can't tell exactly from the code. It would seem like there's a typo or not-recommended pattern in the class name, but that doesn't actually seem to be the case.

Another piece of information: I can sometimes update a measure with `openstudio measure -u` which triggers the error (in addition to doing other cleanup with the files and checksums but doesn't touch name/class_name), remove the error from the measure.xml, re-update the measure with `openstudio measure -u` again, and now it works?!  

thanks!

**Comment by macumber** [comment]
I think this is related to https://github.com/NREL/OpenStudio/issues/5212

**Comment by DavidGoldwasser** [comment]
I've added this and related measure to OS GItHub project and tagged for 3.9.0. One possible related behavior I saw in the past and I want to test if still happens, is that once an error is in the XML file (link example described at top of this issue) you can't clear it out even after measure is fixed with `openstudio measure -u` Instead the XML file has to be opened in text editor and the error removed by hand. This has created confusion at times when not know why fix to measure wasn't working.

**Comment by kbenne** [comment]
Expanding on this a bit, it looks like all of the measures in [https://github.com/NREL/OpenStudio-workflow-gem/blob/39c84e45f152446a92379a501807e2691dba15ab/spec/files/script_error_osw](https://github.com/NREL/OpenStudio-workflow-gem/blob/39c84e45f152446a92379a501807e2691dba15ab/spec/files/script_error_osw) intentionally have various errors for testing purposes. I don't think all of these will cause fatal errors (I tested a number of them by calling `measure -u` after making small changes), but in the case when the measure syntax is invalid, the measure update implementation breaks down because the core of the approach is to parse and load the measure script.

Having said all of this, if someone has an example measure that appears to be valid that we can use to reproduce this issue, I would be interested in it.

**Comment by kbenne** [comment]
From @kflemin, another measure that bubbles up the reported issue is https://github.com/pnnl/openstudio-building-energy-standard-measures-gem/tree/master/lib/measures/GenerateConStrainReport. 

I was able to reproduce the problem and found that this Measure is trying to load the [ConStrain](https://pnnl.github.io/ConStrain/index.html), which we do not include with OpenStudio. As a result OpenStudio fails to load/parse the Measure and the Measure update process fails with the following output.

<img width="1709" alt="Screenshot 2024-10-25 at 9 22 56 AM" src="https://github.com/user-attachments/assets/a4aa5be6-cf8c-42bc-9048-a42dd0f6805f">

One solution is to use the `--python_path` option and point to the ConStrain library.

`openstudio --python_path /path/to/constrain measure update -u /path/to/measure/dir`

**Comment by kbenne** [comment]
Based on what I've seen I think this issue consistently stems from issues in the Measure itself. We can either:

1. Close and do nothing on the OpenStudio side.
2. Consider some adjustments to OpenStudio to help people understand what is going on. There is a callstack reported on standard output, but that level of detail does not make it into the measure.xml file. Should it?

**Comment by DavidGoldwasser** [comment]
When a measure (Ruby or Python) requires custom gems we have put the include outside of the run method. When that library isn't found it can be hard for user to see what is going on. If we have people move those inside of run, then we can add a rescue and check to see if it was loaded, and then runner false with runner.registerError message to user explaining why it failed.

If we can add to measure.xml output that could be useful, or make sure it shows up on verbose log for runner. But neither of those changes seem necessary for 3.9.0. I do want to make sure UO tests run. If we don't have any other specific change to make now we can always make an RC1 and just test it right away so if we need fix in RC2 we can do that.

**Comment by jmarrec** [comment]
I ran into this today, because a measure was using a helpers file in resources/ folder.

FWIW, I think I figured out the issue with openstudio SDK.

place test.py next to your measure.py

```
import importlib.util
import inspect
from pathlib import Path
import openstudio
import sys

print(sys.path)

THIS_PATH = Path(__file__).parent

spec = importlib.util.spec_from_file_location(f"throwaway", THIS_PATH / "measure.py")

module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
class_members = inspect.getmembers(module, lambda x: inspect.isclass(x) and issubclass(x, openstudio.measure.OSMeasure))
assert len(class_members) == 1
measure_name, measure_typeinfo = class_members[0]
print(measure_name)
print(measure_typeinfo)
```

It works with python, because sys.path includes the current script directory:

```
['/Users/julien/Software/Others/Carbonsight/abacus-measures/src/carbonsight-measures/cs_add_outputs', '/Users/julien/.pyenv/versions/3.12.2/lib/python312.zip', '/Users/julien/.pyenv/versions/3.12.2/lib/python3.12', '/Users/julien/.pyenv/versions/3.12.2/lib/python3.12/lib-dynload', '/Users/julien/Virtualenvs/carbonsight/lib/python3.12/site-packages']
```


With openstudio,you don't have it:

```
['/Applications/OpenStudio-3.7.0/lib/../Python', '/Applications/OpenStudio-3.7.0/EnergyPlus/python_standard_lib/lib-dynload', '/Applications/OpenStudio-3.7.0/EnergyPlus/python_standard_lib']
```


Let me work up a full example

**Comment by jmarrec** [comment]
```
GIST_URL=https://gist.github.com/jmarrec/27c8d5c93bbfc233af04b1d307ca45d1/raw/b400d130fb33424a904857b09932f168c5ed17ca
mkdir PythonWithResources && cd PythonWithResources
wget $GIST_URL/measure.py
wget $GIST_URL/measure.xml
mkdir tests && cd tests && wget $GIST_URL/test_python_with_resources.py && cd ..
mkdir resources && cd resources && wget $GIST_URL/helpers.py && cd ..
openstudio measure -u .
```

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/julien/OpenStudio/Measures/temp/./measure.py", line 5, in <module>
    from resources.helpers import freed_from_desire
ModuleNotFoundError: No module named 'resources'
Failed to infer measure name from /Users/julien/OpenStudio/Measures/temp/./measure.py: Error executing Python code
className=
Failed to infer measure name from '/Users/julien/OpenStudio/Measures/temp/./measure.py'
{
	"arguments" : null,
```


[PythonWithResources.zip](https://github.com/user-attachments/files/19966812/PythonWithResources.zip)
